# Generated by Django 6.0 on 2026-04-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default='yes', max_length=16),
            preserve_default=False,
        ),
    ]
