# Generated by Django 6.0 on 2026-04-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_hashed_password_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pepper_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
